# These are supported funding model platforms

github: [sterliakov]
# issuehunt: # Replace with a single IssueHunt username
# polar: # Replace with a single Polar username
buy_me_a_coffee: sterliakov
# thanks_dev: # Replace with a single thanks.dev username
