[package]
name = "toggl-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = "1.13.0"
base64 = "0.22.1"
chrono = { version = "0.4.38", features = ["serde", "unstable-locales"] }
directories-next = "2.0.0"
env_logger = "0.11.5"
iced = { version = "0.13.1", features = ["async-std", "debug", "advanced", "image"] }
iced_aw = { version = "0.11.0", features = ["badge", "menu"], default-features = false }
itertools = "0.13.0"
lazy_static = "1.5.0"
log = { version = "0.4.22", features = ["max_level_trace", "release_max_level_info"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
surf = { version = "2.3.2", features = ["rustls_crate"] }
sys-locale = "0.3.1"

[dev-dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
